# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChatApplication' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ChatApplication
  pod 'SDWebImage'
  pod 'IQKeyboardManagerSwift'
  pod 'MBProgressHUD'
   pod 'ObjectMapper', '~> 3.5'
   pod 'RealmSwift'
   pod 'ObjectMapperAdditions/Realm'
   pod 'GrowingTextView', '0.7.2'
   pod 'Lightbox'
   pod 'ZLImageEditor'
   pod "BSImagePicker", "~> 3.1"
   pod 'ActiveLabel'
   
   post_install do |installer|
       installer.generated_projects.each do |project|
             project.targets.each do |target|
                 target.build_configurations.each do |config|
                     config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
                  end
             end
      end
   end
   
end
